###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
  "email": "ducd@mail.com",
  "password": "duc622"
}
###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
  "email": "duc1@mail.com",
  "password": "duc111"
}
###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
  "email": "duc2@mail.com",
  "password": "duc222"
}